all: create clean

create:	
	pdflatex -shell-escape exp1_micor_bench_identification.tex

clean:
	rm -rf *.aux  *.nav  *.vrb  *.log  *.out *.snm *.toc *.gz *.mtc* *.maf *.fls *.tmp *.bbl *.blg  *.mtc  *.bcf *.xml *.fdb_latexmk figure/*.dep figure/*.dpth figure/*.log figure/*.md5 *.auxlock

