#!/bin/bash

if  [[ $1 = "mkl" ]] 
then
  nomkl="<sysds.native.blas>none</sysds.native.blas>"
  automkl="<sysds.native.blas>mkl</sysds.native.blas>"
  if  [[ $2 = "start" ]] 
  then
    source /opt/intel/bin/compilervars.sh intel64
    # Use '+' as delimiter as '/' is part of the strings
    sed -i "s+$nomkl+$automkl+" ../libraries/SystemDS-config.xml
  elif  [[ $2 = "stop" ]]
  then
    sed -i "s+$automkl+$nomkl+" ../libraries/SystemDS-config.xml
  else
    echo "Pass 'start' or 'stop"
  fi
elif [[ $1 = "codegen" ]]
then
  nocodegen="<sysds.codegen.enabled>false</sysds.codegen.enabled>"
  codegen="<sysds.codegen.enabled>true</sysds.codegen.enabled>"
  if  [[ $2 = "start" ]] 
  then
    # Use '+' as delimiter as '/' is part of the strings
    sed -i "s+$nocodegen+$codegen+" ../libraries/SystemDS-config.xml
  elif  [[ $2 = "stop" ]]
  then
    sed -i "s+$codegen+$nocodegen+" ../libraries/SystemDS-config.xml
  else
    echo "Pass 'start' or 'stop"
  fi
elif [[ $1 = "parallelio" ]]
then
  nopio="<sysds.cp.parallel.io>false</sysds.cp.parallel.io>"
  pio="<sysds.cp.parallel.io>true</sysds.cp.parallel.io>"
  if  [[ $2 = "start" ]] 
  then
    # Use '+' as delimiter as '/' is part of the strings
    sed -i "s+$nopio+$pio+" ../libraries/SystemDS-config.xml
  elif  [[ $2 = "stop" ]]
  then
    sed -i "s+$pio+$nopio+" ../libraries/SystemDS-config.xml
  else
    echo "Pass 'start' or 'stop"
  fi
elif [[ $1 = "lineagespill" ]]
then
  nospill="<sysds.lineage.cachespill>false</sysds.lineage.cachespill>"
  spill="<sysds.lineage.cachespill>true</sysds.lineage.cachespill>"
  if  [[ $2 = "start" ]] 
  then
    # Use '+' as delimiter as '/' is part of the strings
    sed -i "s+$nospill+$spill+" ../libraries/SystemDS-config.xml
  elif  [[ $2 = "stop" ]]
  then
    sed -i "s+$spill+$nospill+" ../libraries/SystemDS-config.xml
  else
    echo "Pass 'start' or 'stop"
  fi
elif [[ $1 = "compassisted" ]]
then
  nocomp="<sysds.lineage.compilerassisted>false</sysds.lineage.compilerassisted>"
  comp="<sysds.lineage.compilerassisted>true</sysds.lineage.compilerassisted>"
  if  [[ $2 = "start" ]] 
  then
    # Use '+' as delimiter as '/' is part of the strings
    sed -i "s+$nocomp+$comp+" ../libraries/SystemDS-config.xml
  elif  [[ $2 = "stop" ]]
  then
    sed -i "s+$comp+$nocomp+" ../libraries/SystemDS-config.xml
  else
    echo "Pass 'start' or 'stop"
  fi
else
  echo "Supported options: mkl, codegen, parallelio, lineagespill, compiler-assisted reuse"
fi
